---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-tektoncd-pipeline-and-push
spec:
  inputs:
    resources:
      - name: plumbing-git
        type: git
      - name: tektoncd-pipeline-git
        type: git
    params:
    - name: UPLOADER_HOST
      description: GO Simple Uploader hostname
  steps:
  - name: build-binaries-and-dockerfiles
    env:
    - name: UPLOADER_USERNAME
      valueFrom:
        secretKeyRef:
          name: openshift-install
          key: uploader-username
    - name: UPLOADER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: openshift-install
          key: uploader-password
    # TODO: change to a parameters since that's probably going to be changed
    # done passably often and we want to commonalize it for the other projects.
    image: openshift/origin-release:golang-1.13
    workingDir: $(inputs.resources.plumbing-git.path)
    script: |
      #!/usr/bin/env bash
      set -ex
      make -C $(inputs.resources.plumbing-git.path)/CI/tasks/build-tektoncd-pipeline \
        build_binary create_dockerfiles \
        PIPELINE_REPOSITORY=$(inputs.resources.tektoncd-pipeline-git.path) \
        OUTPUT_DIR=/workspace/output
