---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-tektoncd-pipeline
spec:
  inputs:
    resources:
      - name: plumbing-git
        type: git
      - name: tektoncd-pipeline-git
        type: git
    params:
    - name: UPLOADER_HOST
      description: GO Simple Uploader hostname
    - name: IMAGE_NAME
      description: Container image
      default: "image-registry.openshift-image-registry.svc:5000/ci-openshift-pipelines/openshift-pipeline-bootstrap"
  steps:
  - name: build-binaries-and-dockerfiles
    env:
    - name: UPLOADER_USERNAME
      valueFrom:
        secretKeyRef:
          name: openshift-install
          key: uploader-username
    - name: UPLOADER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: openshift-install
          key: uploader-password
    image: $(inputs.params.IMAGE_NAME)
    workingDir: $(inputs.resources.plumbing-git.path)
    script: |
      #!/usr/bin/env bash
      set -ex
      make -C $(inputs.resources.plumbing-git.path)/CI/tasks/build-tektoncd-pipeline \
        build_binary create_dockerfiles \
        PIPELINE_REPOSITORY=$(inputs.resources.tektoncd-pipeline-git.path) \
        OUTPUT_DIR=/workspace/output
